### ISSUE TITLE
How to  navigation through sections?

### ISSUE THREAD

**Issue by MIngPAPA** [lingxz/er#2]
Hello, Ling!
I'm new to hugo. With the help of your theme, now I have my rough blog page!

What should I do to set the section navigations or just as the top right corner in  your sample figure(the links like *"about    Tutorials"*)?

Now, my  directory structure under the **content** is:
├── about
│   └── about.md
└── post
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;└── first.md

**Comment by lingxz** [comment]
Hi, 
There are two ways you can do this. You can either specify your main menu in `config.toml` for example like this: 

```toml
[menu]
  [[menu.main]]
    identifier = "tutorial"
    name = "tutorial"
    url = "/tutorial"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
```

or you can indicate it in the frontmatter of the page itself, for example on about.md:
```
+++
title = "About me"
menu = "main"
+++
```
For more information you can look at the [hugo basic example site](https://github.com/gohugoio/hugoBasicExample) which was used for the demo or [hugo's menu documentation](https://gohugo.io/content-management/menus/).
